"""add users table

Revision ID: 9701f4f3d4a6
Revises: 3022fdcc08b6
Create Date: 2026-01-14 12:08:40.432448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9701f4f3d4a6'
down_revision: Union[str, None] = '3022fdcc08b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userotp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('otp', sa.String(length=20), nullable=True),
    sa.Column('otpExpireAt', sa.DateTime(), nullable=True),
    sa.Column('otpVerifiedStatus', mysql.TINYINT(), nullable=True, comment='0->No, 1->Yes'),
    sa.Column('otp_verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', mysql.TINYINT(), nullable=True, comment='-1->delete,1->active,0->inactive'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userotp')
    # ### end Alembic commands ###
