"""add users table

Revision ID: d76b1e4f2e20
Revises: 9701f4f3d4a6
Create Date: 2026-01-15 00:43:25.184433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd76b1e4f2e20'
down_revision: Union[str, None] = '9701f4f3d4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorys', sa.Column('image_url', sa.String(length=200), nullable=True))
    op.add_column('categorys', sa.Column('description', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categorys', 'description')
    op.drop_column('categorys', 'image_url')
    # ### end Alembic commands ###
